-- MySQL Script generated by MySQL Workbench
-- Sun Jan 15 21:14:22 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema aiae
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema aiae
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aiae` DEFAULT CHARACTER SET utf8mb3 ;
USE `aiae` ;

-- -----------------------------------------------------
-- Table `aiae`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aiae`.`empleado` (
  `idempleado` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Edad` INT NOT NULL,
  `Area` VARCHAR(45) NOT NULL,
  `Departamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idempleado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `aiae`.`tarea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aiae`.`tarea` (
  `idtarea` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Fecha_inicio` VARCHAR(45) NOT NULL,
  `Fecha_final` VARCHAR(45) NOT NULL,
  `Empleado_encargado_id` INT NOT NULL,
  `Prioridad` VARCHAR(45) NOT NULL,
  `Porcentaje` INT NOT NULL,
  PRIMARY KEY (`idtarea`),
  INDEX `fk_empleado_tarea` (`Empleado_encargado_id` ASC) VISIBLE,
  CONSTRAINT `fk_empleado_tarea`
    FOREIGN KEY (`Empleado_encargado_id`)
    REFERENCES `aiae`.`empleado` (`idempleado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `aiae`.`subproceso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aiae`.`subproceso` (
  `idsubproceso` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `tarea_id` INT NOT NULL,
  PRIMARY KEY (`idsubproceso`),
  INDEX `fk_tarea_subproceso` (`tarea_id` ASC) VISIBLE,
  CONSTRAINT `fk_tarea_subproceso`
    FOREIGN KEY (`tarea_id`)
    REFERENCES `aiae`.`tarea` (`idtarea`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `aiae`.`proceso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aiae`.`proceso` (
  `idproceso` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `subproceso_id` INT NOT NULL,
  PRIMARY KEY (`idproceso`),
  INDEX `fk_subproceso_proceso` (`subproceso_id` ASC) VISIBLE,
  CONSTRAINT `fk_subproceso_proceso`
    FOREIGN KEY (`subproceso_id`)
    REFERENCES `aiae`.`subproceso` (`idsubproceso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `aiae`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aiae`.`empresa` (
  `idempresa` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `proceso_id` INT NOT NULL,
  PRIMARY KEY (`idempresa`),
  INDEX `fk_proceso_empresa` (`proceso_id` ASC) VISIBLE,
  CONSTRAINT `fk_proceso_empresa`
    FOREIGN KEY (`proceso_id`)
    REFERENCES `aiae`.`proceso` (`idproceso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `aiae`.`registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aiae`.`registro` (
  `idregistro` INT NOT NULL,
  `tareas_id` INT NOT NULL,
  `Fecha_de_registro` VARCHAR(45) NOT NULL,
  `Porcentaje_avance` INT NOT NULL,
  `Descripcion_Avance` TEXT NOT NULL,
  `Documento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idregistro`),
  INDEX `fk_tarea_registro` (`tareas_id` ASC) VISIBLE,
  CONSTRAINT `fk_tarea_registro`
    FOREIGN KEY (`tareas_id`)
    REFERENCES `aiae`.`tarea` (`idtarea`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
